version: '2'
services:
  app:
    build: .
    container_name: alexa_donkey
    environment:
      - TZ=Asia/Hong_Kong
      - VIRTUAL_HOST=alexa.proactivesystem.com.hk
    volumes:
      - ./app:/app
    restart: always
