version: '2'
services:
  app:
    build: .
    container_name: alexa_donkey
    environment:
      - TZ=Asia/Hong_Kong
      - VIRTUAL_HOST=alexa.robocarstore.com
    volumes:
      - ./app:/app
    restart: always

networks:
    default:
        external:
        name: docker04-network